### ISSUE TITLE
Error when running pip install -r requirements.txt

### ISSUE THREAD

**Issue by victorbasu** [defaultnamehere/tinder-detective#15]
When running requirements.txt, everything runs smoothly until: 

error: could not create '/Library/Python/2.7/site-packages/click': Permission denied

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/s0/46d7pqc9183f6t3rtn7js27m0000gn/T/pip-build-bNrv1N/click/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/s0/46d7pqc9183f6t3rtn7js27m0000gn/T/pip-WiJu_h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s0/46d7pqc9183f6t3rtn7js27m0000gn/T/pip-build-bNrv1N/click

Any thoughts?

**Comment by encima** [comment]
You probably want to run the command with `sudo` at the start and enter your admin password (assuming you are on a *nix system)

**Comment by victorbasu** [comment]
Thanks!
