### ISSUE TITLE
ImportError: No module named 'flask'

### ISSUE THREAD

**Issue by graham768** [defaultnamehere/tinder-detective#21]
Flask is installed in my virtualenv after running
`pip install -r requirements.txt`
as seen below

```
(venv) $ pip list
click (6.6)
Flask (0.11.1)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
pip (8.1.2)
python-dateutil (2.5.3)
requests (2.10.0)
setuptools (24.3.0)
six (1.10.0)
Werkzeug (0.11.10)
wheel (0.29.0)
```

yet I get the error 

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, render_template
ImportError: No module named 'flask'
```

**Comment by danielvinson** [comment]
Stackoverflow told me to follow these steps (which worked):

sudo aptitude install python3-setuptools
sudo easy_install3 pip
sudo pip3.4 install -r requirements.txt

**Comment by grahovam** [comment]
do `pip3 install -r requirements.txt` instead

**Comment by graham768** [comment]
Thank you, that solved it!
