### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by ericlw** [defaultnamehere/tinder-detective#5]

**Comment by idkm23** [comment]
how did you fix this i dont understand

**Comment by idkm23** [comment]
i am getting this as well and not sure what i am doing wrong

**Comment by idkm23** [comment]
well it just fixed itself, i just had to wait a bit. probably because I had just activated my tinder account.

**Comment by ericlw** [comment]
@idkm23 you have to activate Tinder Social for results to show in the groups response, and then you have to have friends that also activated it (unless they were auto opted-in in Australia)
